from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (
    AboutView,
    AdminAdviceForTodayCreateView,
    AdminAdviceForTodayListView,
    AdminAdviceForTodayUpdateView,
    AdminAboutPageUpdateView,
    AdminAssessmentDetailView,
    AdminAssessmentListView,
    AdminBookingRequestCancelView,
    AdminBookingRequestCreateView,
    AdminBookingRequestDetailView,
    AdminBookingRequestListView,
    AdminBookingRequestUpdateView,
    AdminBookingPaymentToggleView,
    AdminClientCreateView,
    AdminContactMessageDetailView,
    AdminContactMessageListView,
    AdviceForTodayDetailView,
    AdminDashboardView,
    AdminProfileView,
    AdminQuestionCreateView,
    AdminQuestionDeleteView,
    AdminQuestionListView,
    AdminQuestionUpdateView,
    AdminServiceCreateView,
    AdminServiceCategoryCreateView,
    AdminServiceDeleteView,
    AdminServiceListView,
    AdminServiceUpdateView,
    AdminTherapistCreateView,
    AdminTherapistListView,
    AdminTherapistUpdateView,
    ArticleDetailView,
    ArticleManageCreateView,
    ArticleManageDeleteView,
    ArticleManageListView,
    ArticleManageUpdateView,
    ArticleListView,
    AssessmentResultsView,
    AssessmentView,
    BookingRequestCreateView,
    BookingThanksView,
    ClientBookingCancelView,
    ClientBookingPostponeView,
    ClientDashboardView,
    ClientProfileView,
    ClientRegistrationView,
    ContactView,
    CookiesView,
    DashboardRedirectView,
    HomeView,
    LocalPasswordResetCompleteView,
    LocalPasswordResetView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    PrivacyView,
    ProfileRedirectView,
    RoleAwareLoginView,
    ServiceDetailView,
    ServiceListView,
    TermsView,
    TherapistDashboardView,
    TherapistDetailRedirectView,
    TherapistBookingPaymentToggleView,
    TherapistAvailabilityCreateView,
    TherapistAvailabilityDeleteView,
    TherapistAvailabilityListView,
    TherapistAvailabilityUpdateView,
    TherapistListRedirectView,
    TherapistProfileView,
    TherapistServiceCategoryCreateView,
    TherapistServiceCreateView,
    TherapistServiceDeleteView,
    TherapistServiceLinkView,
    TherapistServiceListView,
    TherapistServiceUpdateView, TherapistDetailView, ArticleCategoryCreateView,
)

app_name = "aterapija"



urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("services/", ServiceListView.as_view(), name="services"),
    path("services/<slug:slug>/", ServiceDetailView.as_view(), name="service_detail"),
    path("therapists/", TherapistListRedirectView.as_view(), name="therapists"),
    path("therapists/<int:pk>/", TherapistDetailView.as_view(), name="therapist_detail"),
    path("articles/", ArticleListView.as_view(), name="articles"),
    path("articles/<slug:slug>/", ArticleDetailView.as_view(), name="article_detail"),
    path("dashboard/articles/", ArticleManageListView.as_view(), name="article_manage_list"),
    path("dashboard/articles/categories/add/", ArticleCategoryCreateView.as_view(),name="article_category_add",),
    path("dashboard/articles/add/", ArticleManageCreateView.as_view(), name="article_manage_add"),
    path("dashboard/articles/<int:pk>/edit/", ArticleManageUpdateView.as_view(), name="article_manage_edit"),
    path("dashboard/articles/<int:pk>/delete/", ArticleManageDeleteView.as_view(), name="article_manage_delete"),
    path("advice-for-today/<int:pk>/", AdviceForTodayDetailView.as_view(), name="advice_detail"),
    path("blog/", ArticleListView.as_view(), name="blog"),
    path("booking/", BookingRequestCreateView.as_view(), name="booking_create"),
    path("booking/service/<slug:service_slug>/", BookingRequestCreateView.as_view(), name="booking_for_service"),
    path(
        "booking/service/<slug:service_slug>/therapist/<int:therapist_pk>/",
        BookingRequestCreateView.as_view(),
        name="booking_for_service_and_therapist",
    ),
    path("booking/thanks/", BookingThanksView.as_view(), name="booking_thanks"),
    path("assessment/", AssessmentView.as_view(), name="assessment"),
    path("assessment/results/", AssessmentResultsView.as_view(), name="assessment_results"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("accounts/register/", ClientRegistrationView.as_view(), name="register"),
    path("accounts/login/", RoleAwareLoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(template_name="registration/aterapija_logged_out.html"), name="logout"),
    path(
        "accounts/password-reset/",
        LocalPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "accounts/reset/done/",
        LocalPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/mark-all-read/", NotificationMarkAllReadView.as_view(), name="notifications_mark_all_read"),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view(), name="notification_mark_read"),
    path("dashboard/", DashboardRedirectView.as_view(), name="dashboard"),
    path("admin-dashboard/", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("admin-dashboard/about/edit/", AdminAboutPageUpdateView.as_view(), name="admin_about_edit"),
    path("admin-dashboard/profile/", AdminProfileView.as_view(), name="admin_profile"),
    path("admin-dashboard/services/", AdminServiceListView.as_view(), name="admin_service_list"),
    path("admin-dashboard/services/add/", AdminServiceCreateView.as_view(), name="admin_service_add"),
    path(
        "admin-dashboard/services/categories/add/",
        AdminServiceCategoryCreateView.as_view(),
        name="admin_service_category_add",
    ),
    path("admin-dashboard/services/<int:pk>/edit/", AdminServiceUpdateView.as_view(), name="admin_service_edit"),
    path("admin-dashboard/services/<int:pk>/delete/", AdminServiceDeleteView.as_view(), name="admin_service_delete"),
    path("admin-dashboard/therapists/", AdminTherapistListView.as_view(), name="admin_therapist_list"),
    path("admin-dashboard/therapists/add/", AdminTherapistCreateView.as_view(), name="admin_therapist_add"),
    path("admin-dashboard/therapists/<int:pk>/edit/", AdminTherapistUpdateView.as_view(), name="admin_therapist_edit"),
    path("admin-dashboard/advice-for-today/", AdminAdviceForTodayListView.as_view(), name="admin_advice_list"),
    path(
        "admin-dashboard/advice-for-today/add/",
        AdminAdviceForTodayCreateView.as_view(),
        name="admin_advice_add",
    ),
    path(
        "admin-dashboard/advice-for-today/<int:pk>/edit/",
        AdminAdviceForTodayUpdateView.as_view(),
        name="admin_advice_edit",
    ),
    path(
        "admin-dashboard/help-me-choose/",
        AdminAssessmentListView.as_view(),
        name="admin_assessment_list",
    ),
    path(
        "admin-dashboard/help-me-choose/questions/",
        AdminQuestionListView.as_view(),
        name="admin_question_list",
    ),
    path(
        "admin-dashboard/help-me-choose/questions/add/",
        AdminQuestionCreateView.as_view(),
        name="admin_question_add",
    ),
    path(
        "admin-dashboard/help-me-choose/questions/<int:pk>/edit/",
        AdminQuestionUpdateView.as_view(),
        name="admin_question_edit",
    ),
    path(
        "admin-dashboard/help-me-choose/questions/<int:pk>/delete/",
        AdminQuestionDeleteView.as_view(),
        name="admin_question_delete",
    ),
    path(
        "admin-dashboard/help-me-choose/<int:pk>/",
        AdminAssessmentDetailView.as_view(),
        name="admin_assessment_detail",
    ),
    path(
        "admin-dashboard/contact-messages/",
        AdminContactMessageListView.as_view(),
        name="admin_contact_message_list",
    ),
    path(
        "admin-dashboard/contact-messages/<int:pk>/",
        AdminContactMessageDetailView.as_view(),
        name="admin_contact_message_detail",
    ),
    path(
        "admin-dashboard/booking-requests/",
        AdminBookingRequestListView.as_view(),
        name="admin_booking_request_list",
    ),
    path(
        "admin-dashboard/booking-requests/add/",
        AdminBookingRequestCreateView.as_view(),
        name="admin_booking_request_add",
    ),
    path(
        "admin-dashboard/booking-requests/<int:pk>/",
        AdminBookingRequestDetailView.as_view(),
        name="admin_booking_request_detail",
    ),
    path(
        "admin-dashboard/booking-requests/<int:pk>/edit/",
        AdminBookingRequestUpdateView.as_view(),
        name="admin_booking_request_edit",
    ),
    path(
        "admin-dashboard/booking-requests/<int:pk>/cancel/",
        AdminBookingRequestCancelView.as_view(),
        name="admin_booking_request_cancel",
    ),
    path(
        "admin-dashboard/booking-requests/<int:pk>/payment/",
        AdminBookingPaymentToggleView.as_view(),
        name="admin_booking_payment_toggle",
    ),
    path(
        "admin-dashboard/clients/add/",
        AdminClientCreateView.as_view(),
        name="admin_client_add",
    ),
    path("therapist-dashboard/", TherapistDashboardView.as_view(), name="therapist_dashboard"),
    path(
        "therapist-dashboard/bookings/<int:pk>/payment/",
        TherapistBookingPaymentToggleView.as_view(),
        name="therapist_booking_payment_toggle",
    ),
    path("therapist-dashboard/profile/", TherapistProfileView.as_view(), name="therapist_profile"),
    path("therapist-dashboard/services/", TherapistServiceListView.as_view(), name="therapist_service_list"),
    path("therapist-dashboard/services/add/", TherapistServiceCreateView.as_view(), name="therapist_service_add"),
    path(
        "therapist-dashboard/services/categories/add/",
        TherapistServiceCategoryCreateView.as_view(),
        name="therapist_service_category_add",
    ),
    path("therapist-dashboard/services/link/", TherapistServiceLinkView.as_view(), name="therapist_service_link"),
    path(
        "therapist-dashboard/services/<int:pk>/edit/",
        TherapistServiceUpdateView.as_view(),
        name="therapist_service_edit",
    ),
    path(
        "therapist-dashboard/services/<int:pk>/delete/",
        TherapistServiceDeleteView.as_view(),
        name="therapist_service_delete",
    ),
    path(
        "therapist-dashboard/availability/",
        TherapistAvailabilityListView.as_view(),
        name="therapist_availability_list",
    ),
    path(
        "therapist-dashboard/availability/add/",
        TherapistAvailabilityCreateView.as_view(),
        name="therapist_availability_add",
    ),
    path(
        "therapist-dashboard/availability/<int:pk>/edit/",
        TherapistAvailabilityUpdateView.as_view(),
        name="therapist_availability_edit",
    ),
    path(
        "therapist-dashboard/availability/<int:pk>/delete/",
        TherapistAvailabilityDeleteView.as_view(),
        name="therapist_availability_delete",
    ),
    path("client-dashboard/", ClientDashboardView.as_view(), name="client_dashboard"),
    path("client-dashboard/profile/", ClientProfileView.as_view(), name="client_profile"),
    path(
        "client-dashboard/bookings/<int:pk>/cancel/",
        ClientBookingCancelView.as_view(),
        name="client_booking_cancel",
    ),
    path(
        "client-dashboard/bookings/<int:pk>/postpone/",
        ClientBookingPostponeView.as_view(),
        name="client_booking_postpone",
    ),
    path("profile/", ProfileRedirectView.as_view(), name="profile"),
    path("privacy/", PrivacyView.as_view(), name="privacy"),
    path("cookies/", CookiesView.as_view(), name="cookies"),
    path("terms/", TermsView.as_view(), name="terms"),
]
