# Generated by Django 6.0.6 on 2026-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0004_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceForToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Advice for Today', max_length=160)),
                ('body', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='advice_for_today/')),
                ('published_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'advice for today',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
