# Generated by Django 6.0.6 on 2026-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='therapist',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
