# Generated by Django 6.0.6 on 2026-06-10 07:38

import django.db.models.deletion
from django.db import migrations, models


def normalize_booking_statuses(apps, schema_editor):
    BookingRequest = apps.get_model("aterapija", "BookingRequest")
    BookingRequest.objects.filter(status__in=["pending", "confirmed"]).update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0008_adminprofile_phone_therapist_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_booking_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('cancelled', 'Cancelled')], default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='TherapistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='aterapija.therapist')),
            ],
            options={
                'verbose_name_plural': 'therapist availability',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
