# Generated by Django 6.0.6 on 2026-06-10 08:18

from django.db import migrations, models


def backfill_end_dates(apps, schema_editor):
    TherapistAvailability = apps.get_model("aterapija", "TherapistAvailability")
    for block in TherapistAvailability.objects.filter(end_date__isnull=True):
        block.end_date = block.date
        block.save(update_fields=["end_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0009_alter_bookingrequest_status_therapistavailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapistavailability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'therapist unavailable time', 'verbose_name_plural': 'therapist unavailable times'},
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(backfill_end_dates, migrations.RunPython.noop),
    ]
