# Generated by Django 6.0.6 on 2026-06-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0010_alter_therapistavailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='experience',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='therapist',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='therapist',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='therapist_profiles/'),
        ),
    ]
