# Generated by Django 6.0.6 on 2026-06-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0011_therapist_experience_therapist_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=160)),
                ('main_text', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='about_page/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wellbeingquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text input'), ('textarea', 'Textarea'), ('single', 'Single choice'), ('multiple', 'Multiple choice')], default='multiple', max_length=20),
        ),
        migrations.CreateModel(
            name='WellbeingTextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='aterapija.wellbeingassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='aterapija.wellbeingquestion')),
            ],
            options={
                'ordering': ['question__order', 'question__id'],
            },
        ),
    ]
