# Generated by Django 6.0.6 on 2026-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_translated_to_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='article',
            name='title_lt',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='title_lt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='therapist',
            name='bio_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='bio_lt',
            field=models.TextField(blank=True),
        ),
    ]
