# Generated by Django 6.0.6 on 2026-07-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0015_backfill_lithuanian_content_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='main_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_eyebrow',
            field=models.CharField(default='Begin gently', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_title',
            field=models.CharField(default='Ready to take care of yourself?', max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_page/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.TextField(default='A gentle space where therapeutic care, body awareness and mindful presence meet.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='Therapy that helps you return to yourself', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_1_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_1_title',
            field=models.CharField(default='Book', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_2_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_2_title',
            field=models.CharField(default='Assess', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_3_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_3_title',
            field=models.CharField(default='Therapy', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_4_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_4_title',
            field=models.CharField(default='Integrate', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_title',
            field=models.CharField(default='How therapy works', max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_eyebrow',
            field=models.CharField(default='Our story', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_page/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_text_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_text_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_title',
            field=models.CharField(default='Healing begins when we feel safe enough to understand ourselves.', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_eyebrow',
            field=models.CharField(default='Therapist', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_title',
            field=models.CharField(default='Meet your therapist', max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
