# Generated by Django 6.0.6 on 2026-07-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0016_remove_aboutpage_image_remove_aboutpage_main_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_image',
        ),
    ]
