# Generated by Django 6.0.6 on 2026-07-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0017_remove_aboutpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='quote',
            field=models.CharField(blank=True, help_text='Short personal quote shown on the therapist detail page.', max_length=255),
        ),
    ]
