# Generated by Django 6.0.6 on 2026-07-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0018_therapist_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advicefortoday',
            name='image',
        ),
        migrations.AddField(
            model_name='advicefortoday',
            name='quote',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='advicefortoday',
            name='title',
            field=models.CharField(default="Today's Insight", max_length=160),
        ),
    ]
