# Generated by Django 6.0.6 on 2026-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0019_remove_advicefortoday_image_advicefortoday_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='cta_eyebrow_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_eyebrow_lt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_text_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_title_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_title_lt',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_lt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_1_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_1_text_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_1_title_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_1_title_lt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_2_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_2_text_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_2_title_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_2_title_lt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_3_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_3_text_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_3_title_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_3_title_lt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_4_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_4_text_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_4_title_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_4_title_lt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_title_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='process_title_lt',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_eyebrow_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_eyebrow_lt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_text_1_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_text_1_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_text_2_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_text_2_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_title_en',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_title_lt',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_eyebrow_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_eyebrow_lt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_intro_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_intro_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_title_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='therapist_title_lt',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_lt',
            field=models.TextField(blank=True),
        ),
    ]
