# Generated by Django 6.0.6 on 2026-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0020_aboutpage_cta_eyebrow_en_aboutpage_cta_eyebrow_lt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_eyebrow',
            field=models.CharField(default='About A Terapija', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_eyebrow_lt',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
