# Generated by Django 6.0.6 on 2026-08-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0022_backfill_bilingual_about_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.TextField(default='A gentle space where therapeutic care, body awareness and mindful presence meet'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_title',
            field=models.CharField(default='Healing begins when we feel safe enough to understand ourselves', max_length=250),
        ),
    ]
