# Generated by Django 6.0.6 on 2026-08-26 14:59

from django.db import migrations, models


def backfill_lithuanian_category_content(apps, schema_editor):
    service_category = apps.get_model("aterapija", "ServiceCategory")
    for category in service_category.objects.all():
        updates = []
        if not category.name_lt:
            category.name_lt = category.name
            updates.append("name_lt")
        if not category.description_lt:
            category.description_lt = category.description
            updates.append("description_lt")
        if updates:
            category.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('aterapija', '0023_alter_aboutpage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_lt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_lt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(backfill_lithuanian_category_content, migrations.RunPython.noop),
    ]
